language: java
install: true
os: linux
dist: trusty
jdk:
- openjdk11

branches:
- develop

# build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew clean build --scan -s

# deploy
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: pws.comsysto@reply.de
  password:
    secure: TLCPdqU01jQJj0PKWMxBkFeByI0zwcaxz8omYPymUG0ukqF91ZL/eap4zvYJx7swoaufhureeqzGbjHWhDokABjPbsqwiuM9zqTU11/wfqmW9D5QpLDLul3z+O0npyFGnuxXkSiNC7pvUH2QBdg+PxCmr3URCikF0pseST67qzp+rwOPO364OwiLBLrZmL+jR8pRLBY0V4IEkZlEZa8M2tq/SXUKRvBBwv5YfKUsVIret5p3BTCSsy/W3UCWIa4u9ROKAoxsqM/ECU+UgcXaPRyi4HVNbFPk5ge9Tsn83ocRvIlYdmpv7ZnDeSbm1FF1ydVRi1hhCjzmGaVym2skCVWdZhobRPQiDZveu13tpJlDYxfZzp6DBj7HBUWrBuXVJr2o9lIK98jBBD1b24Em3bz3Nw0lbdLq93ty+JMkliIvImsQVKqwYUmDyjEtqc3mV1UVIhizHn/aZNBX7Qi8xLr2/yStxoR5UidGvLT3jR1PeeM6lC7XtqvygQPRCv0FzXjfmkjXc3nNBqX6YDVja5BQm0Ki/ggqt6fIvwWn6BfRVpTCqDrMHfetg7sOp4jPpAUUhnMcPmH3lS2H3yMsFjbBbnFPPfauE0hEkph/7HrgWyUypTzwHm16320e5h0KGf5xKhp55e/wOk+on4f6JNjU3y/6xJhJwl7t9pf+j4Q=
  organization: mvg
  space: development
  on:
    repo: comsysto/agile-dev-starter-project
    branch: develop
