name: Couldfoundry CI Lab

on: [push]

jobs:
  # enable once action is implemented
  ## build:
  ##   runs-on: ubuntu-latest
  ##   steps:
  ##   - uses: actions/checkout@v1
  ##   - name: Set up JDK 11
  ##     uses: actions/setup-java@v1
  ##     with:
  ##       java-version: 11
  ##   - name: Build with Gradle
  ##     run: ./gradlew build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloudfoundry deployment
        id: cf
        uses: comsysto/cloudfoundry-action@master
        with:
          api: ${{ secrets.CF_API }}
          org: 'mvg'
          space: 'dev'
          user: ${{ secrets.CF_USER }}
          password: ${{ secrets.CF_PASSWORD }}
      - name: Cloudfoundry deployment result
        run: echo "Deployment was ${{ steps.cf.outputs.deploymentResult }}"
