name: Couldfoundry CI Lab

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private action
        uses: actions/checkout@v1
      - uses: ./
      - name: Cloudfoundry deployment
        id: cf
        uses: comsysto/cloudfoundry-action@master
        with:
          myInput: 'cloudfoundry'
      - name: Cloudfoundry deployment result
        run: echo "Deployment was ${{ steps.cf.outputs.deploymentResult }}"
