name: Couldfoundry CI Lab
on: [push]
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Prepare deploymentArchive
      #uses: comsysto/deployment-information-action/create@master
      #with:
      #  archive-name: deploymentArchive
      #  target-path: build/libs
      run: |
        cp ./manifest.yaml ./build/libs

        archivesBaseName="$(./gradlew properties -q | grep '^archivesBaseName:' | awk '{print $2}')"
        version="$(./gradlew properties  -q | gre§p '^version:' | awk '{print $2}')"

        cat >./build/libs/deploymentInfo.json <<EOL
        {
          "artifactPath": "deploymentArchive/${archivesBaseName}-${version}.jar",
          "manifestPath": "deploymentArchive/manifest.yaml"
        }
        EOL

        chmod +x ./build/libs/deploymentInfo.json

    - run: cp ./manifest.yaml ./build/libs
    - name: Upload deploymentArchive
      uses: actions/upload-artifact@v1
      with:
        name: deploymentArchive
        path: build/libs
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: cf login to https://api.run.pivotal.io
        uses: comsysto/cloudfoundry-action/auth@v1
        with:
          api: 'https://api.run.pivotal.io'
          user: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
      - name: cf target -o mvg -s development
        uses: comsysto/cloudfoundry-action/cli@v1
        with:
          args: target -o mvg -s development
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: deploymentArchive
      - name: Read deploymentInfo.json
        id: deploymentInfo
        uses: comsysto/deployment-information-action/read@release
        with:
          archive-path: deploymentArchive
      - name: cf push
        uses: comsysto/cloudfoundry-action/cli@v1
        with:
          args: push -f ${{ steps.deploymentInfo.outputs.cf-manifest-path }} -p ${{ steps.deploymentInfo.outputs.artifact-path }} --no-start
