name: Couldfoundry CI Lab
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Prepare deploymentArchive
      run: |
        archivesBaseName="$(./gradlew properties -q | grep '^archivesBaseName:' | awk '{print $2}')"
        version="$(./gradlew properties  -q | grep '^version:' | awk '{print $2}')"

        echo "archivePath: deploymentArchive/${archivesBaseName}-${version}.jar" >> ./build/libs/deployment.yaml

        cp ./manifest.yaml ./build/libs
        echo "manifestPath: deploymentArchive/manifest.yaml" >> ./build/libs/deployment.yaml
    - name: Upload deploymentArchive
      uses: actions/upload-artifact@v1
      with:
        name: deploymentArchive
        path: build/libs
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: cf login to https://api.run.pivotal.io
        uses: comsysto/cloudfoundry-action/auth@develop
        with:
          api: 'https://api.run.pivotal.io'
          user: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
      - name: cf target -o mvg -s development
        uses: comsysto/cloudfoundry-action/cli@develop
        with:
          args: target -o mvg -s development
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: deploymentArchive
      - name: Read deployment.yaml
        id: deploymentInfo
        run: |
          less deploymentArchive/deployment.yaml
          export archivePath=deploymentArchive/agile-dev-starter-0.0.1-SNAPSHOT.jar
          export manifestPath=deploymentArchive/manifest.yaml
          echo "::set-env name=archivePath::deploymentArchive/agile-dev-starter-0.0.1-SNAPSHOT.jar"
          echo "::set-env name=manifestPath::deploymentArchive/manifest.yaml"
      - name: cf push
        uses: comsysto/cloudfoundry-action/cli@develop
        with:
          args: push -f $manifestPath -p $archivePath --no-start
