name: Couldfoundry CI Lab
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Add manifest to build result
      run: cp ./manifest.yaml ./build/libs
    - uses: actions/upload-artifact@v1
      with:
        name: github-action-lab-artifact
        path: build/libs
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downlaod artifact
        uses: actions/download-artifact@v1
        with:
          name: github-action-lab-artifact
      - name: Cloudfoundry deployment
        id: cf
        uses: comsysto/cloudfoundry-action@master
        with:
          api: 'https://api.run.pivotal.io'
          org: 'mvg'
          space: 'development'
          user: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          artifactDir: github-action-lab-artifact
      - name: Cloudfoundry deployment result
        run: echo "Deployment was ${{ steps.cf.outputs.deploymentResult }}"
